#:schema node_modules/wrangler/config-schema.json
name = "commet-telescope"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
ENCRYPTED_PREVIEW_PUBLIC_KEY_B64 = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6K3NBaThQc1Q0UXdqVi8reFhLMAp2d2F2WkpFamt3SnlGT0RHV2tvbzdxQjg3WTJ5VTYvQzRjc3VsNmtRcHhCRnU5SUQ3bUNhdkFscjkzL2M3MFFtCnNnWDc5MVc3b09TcHZ5ZWZmSmU1aWx1emFnbFovS1dZbzZCYzBRYWpLVDhyTGRJNXZVbGpWTXl4L25SOXJJaFkKUHZTSmhTRkxDMlp5VWhoVGIvWmVMbTBhckV0R2V5Zm8xVjNuTEdzSlpKeDEyVUs4RTBGcEtQMTRTN1drZTl6TQplMDVQRENVL2xsRVFwVWdRT0pJOVZuamk3MUZnb2NpaTc2YVNVTGhYYWxHalFJekJHS2liNU1JWWxiMFpnZjhrCndLa1JnNklyTnQ1a2phZDRQb1JLb2N4ajN5bHZ1eEV0TU41ODJuaTNsTzRnaTF1enpWdkZ0SkJ6cmhOTWpUUEMKcFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
