#:schema node_modules/wrangler/config-schema.json
name = "telescope"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
ENCRYPTED_PREVIEW_PUBLIC_KEY_B64 = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzSG02QldzQUxOUzhRUkdYMTl3Nwo2MHd6eHRXT0ZESktVMnlnclVrc0RaQk5qZkVyVVNFbmx5ZnRoR2xrRGJYTGo1akN3MzUwaUNQRUJMMDJmZEFNCmkxdnQ2UTlvOGwwS2xVVys1WmtQZHhQcVMyUCtmemREMFhaeVRUU0hLWE9zeHhXNkJvVHlldGtqWGp5UWNVa2UKODFRQ0JaSGJyQnJEZGR6alphbnhLdFRoRFRzNDUybE9oZFNHL29kMHkzLzhJN1lNWjh2UnJvUFRwMERYU2Y3WQpWTVZzR3JoTjVqK1Vuc1o5TUZUUmxzYy9uLzRNdVAzVG9teXF4RmMzWExKYXFnQ0xqbnVYYnVJWjJiVkFiT0R2CkJhMFdReDRESTd2ZzlhUWM3bDFLSE1Kc1psa1o3eWlLb2x4WUtVUmRIVEYxUWd0Vk8wTi94d0E5U1BJSGtHUEoKQndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
